export const STORIES = [
	{
		id: "page-populated",
		group: "Pages",
		title: "Console — populated room",
		docs: "Complete conversation shell with real channel rail, transcript, composer, and agent controls.",
	},
	{
		id: "page-empty",
		group: "Pages",
		title: "Console — empty room",
		docs: "Selected room with no messages and a direct first-message action.",
	},
	{
		id: "page-offline",
		group: "Pages",
		title: "Console — offline",
		docs: "Disconnected shell with stale-room context and retry action.",
	},
	{
		id: "page-load-failure",
		group: "Pages",
		title: "Console — load failure",
		docs: "Failed room-history request with visible recovery action.",
	},
	{
		id: "page-thread",
		group: "Pages",
		title: "Console — open thread",
		docs: "Populated room with its real focused reply panel and thread composer.",
	},
	{
		id: "page-plans",
		group: "Pages",
		title: "Plans — populated",
		docs: "Real PlansView backed only by an isolated in-memory story response seam.",
	},
	{
		id: "page-changes",
		group: "Pages",
		title: "Changes — working tree",
		docs: "Real ChangesView showing working files and a unified diff from story fixtures.",
	},
	{
		id: "comp-transcript",
		group: "Components",
		title: "Transcript",
		docs: "Real message rendering with Markdown, mentions, reactions, code, and thread affordances.",
	},
	{
		id: "comp-composer",
		group: "Components",
		title: "Composer",
		docs: "Real composer with keyboard guidance and attachment picker behavior.",
	},
	{
		id: "comp-thread",
		group: "Components",
		title: "Thread panel",
		docs: "Real thread panel populated with a root and replies.",
	},
	{
		id: "comp-agents",
		group: "Components",
		title: "Agent panel",
		docs: "Real agent sheet. Switch among Members, Operations, and Accounts tabs.",
	},
	{
		id: "comp-ops",
		group: "Components",
		title: "Agent operations",
		docs: "Agent sheet starts on Members; select Operations to inspect logs, injection, and stop controls.",
	},
	{
		id: "comp-new-channel",
		group: "Components",
		title: "Create room dialog",
		docs: "Real validated create-room dialog using the story-only call seam.",
	},
	{
		id: "comp-new-agent",
		group: "Components",
		title: "Create agent dialog",
		docs: "Real identity, runtime preference, room, and system-prompt form.",
	},
	{
		id: "state-empty",
		group: "States",
		title: "Transcript — empty",
		docs: "Quiet-room state and focus-forward first-message action.",
	},
	{
		id: "state-offline",
		group: "States",
		title: "Transcript — offline",
		docs: "Daemon connectivity loss with explicit retry.",
	},
	{
		id: "state-load-failure",
		group: "States",
		title: "Transcript — load failure",
		docs: "History failure distinguished from connectivity loss.",
	},
];
